'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const enc=new TextEncoder(), dec=new TextDecoder();
const DB_KEY='relay.workspace.v1', META_KEY='relay.meta.v1';
let key=null, apiKey='', provider='tokenharbor', pendingApproval=null, state={memories:[],tasks:[],messages:[]}, busy=false;
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))), unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(pass,salt){const base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptData(data,k=key,saltValue=null){const iv=crypto.getRandomValues(new Uint8Array(12)), salt=saltValue||crypto.getRandomValues(new Uint8Array(16));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(JSON.stringify(data)));return {format:'relay-encrypted-v1',kdf:'PBKDF2-SHA-256',iterations:310000,cipher:'AES-256-GCM',salt:b64(salt),iv:b64(iv),data:b64(cipher)}}
async function decryptData(pack,k){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(pack.iv)},k,unb64(pack.data));return JSON.parse(dec.decode(plain))}
async function persist(){if(!key)return;const meta=JSON.parse(localStorage.getItem(META_KEY));localStorage.setItem(DB_KEY,JSON.stringify(await encryptData(state,key,unb64(meta.salt))));$('#saveState').textContent='Encrypted · saved'}
async function unlock(){const pass=$('#passphrase').value;if(pass.length<10){$('#lockStatus').textContent='Use at least 10 characters.';return}$('#unlock').disabled=true;$('#lockStatus').textContent='Deriving encryption key…';try{let meta=JSON.parse(localStorage.getItem(META_KEY)||'null');if(!meta){const salt=crypto.getRandomValues(new Uint8Array(16));meta={salt:b64(salt),proof:null};key=await derive(pass,salt);state={memories:[],tasks:[],messages:[]};localStorage.setItem(META_KEY,JSON.stringify(meta));await persist()}else{key=await derive(pass,unb64(meta.salt));const pack=JSON.parse(localStorage.getItem(DB_KEY)||'null');if(pack)state=await decryptData(pack,key)}$('#lock').classList.add('hidden');$('#app').classList.remove('hidden');$('#passphrase').value='';render()}catch(e){key=null;$('#lockStatus').textContent='Could not unlock. Check the passphrase.'}finally{$('#unlock').disabled=false}}
function lock(){key=null;apiKey='';state={memories:[],tasks:[],messages:[]};$('#apiKey').value='';$('#app').classList.add('hidden');$('#lock').classList.remove('hidden');$('#lockStatus').textContent='Workspace locked.'}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){renderMessages();renderMemory();renderTasks();$('#memoryCount').textContent=state.memories.length;$('#taskCount').textContent=state.tasks.filter(t=>!t.done).length}
function renderMessages(){const box=$('#messages');if(!state.messages.length)return;box.innerHTML=state.messages.map(m=>`<div class="message ${m.role}">${m.role==='assistant'?'<div class="role">RELAY</div>':''}<div class="bubble">${esc(m.content)}</div></div>`).join('');box.scrollTop=box.scrollHeight}
function renderMemory(){const box=$('#memoryList');box.innerHTML=state.memories.length?state.memories.map((m,i)=>`<article class="card"><div class="grow"><h3>${esc(m.title)}</h3><p>${esc(m.content)}</p></div><button data-del-m="${i}">×</button></article>`).join(''):'<p class="muted">No memory yet. Ask Relay to remember something.</p>'}
function renderTasks(){const open=state.tasks.filter(t=>!t.done);$('#goalPulse').innerHTML=open.length?`<b>FOLLOW-THROUGH</b>${open.length} open ${open.length===1?'task':'tasks'}. Next up: ${esc(open[0].title)}`:'<b>CLEAR DECK</b>No open tasks. Ask Relay to turn a goal into the next concrete step.';const box=$('#taskList');box.innerHTML=state.tasks.length?state.tasks.map((t,i)=>`<article class="card ${t.done?'done':''}"><button class="check" data-toggle-t="${i}">${t.done?'✓':''}</button><div class="grow"><h3>${esc(t.title)}</h3><p>${esc(t.detail||'')}</p></div><button data-del-t="${i}">×</button></article>`).join(''):'<p class="muted">No tasks yet. Relay can build a task list from a conversation.</p>'}
function showApproval(){if(!pendingApproval)return;$('#approvalTitle').textContent='Approval needed';$('#approvalDetail').textContent=`${pendingApproval.action} · ${pendingApproval.reason}`;$('#approval').classList.remove('hidden')}
function trace(s){$('#runTrace').textContent=s;$('#runTrace').classList.toggle('hidden',!s)}
const toolDefs=[
{name:'memory_save',description:'Save a durable user fact or preference.',parameters:{type:'object',properties:{title:{type:'string'},content:{type:'string'}},required:['title','content']}},
{name:'memory_search',description:'Search private memory by keywords.',parameters:{type:'object',properties:{query:{type:'string'}},required:['query']}},
{name:'task_add',description:'Add a task.',parameters:{type:'object',properties:{title:{type:'string'},detail:{type:'string'}},required:['title']}},
{name:'task_complete',description:'Mark a task complete by exact or partial title.',parameters:{type:'object',properties:{title:{type:'string'}},required:['title']}},
{name:'propose_sensitive_action',description:'Pause and ask for explicit approval before any external message, public share, destructive action, purchase, credential use, or privacy-sensitive operation. This only proposes; it does not execute.',parameters:{type:'object',properties:{action:{type:'string'},reason:{type:'string'}},required:['action','reason']}},
{name:'task_list',description:'List current tasks.',parameters:{type:'object',properties:{include_done:{type:'boolean'}}}},
{name:'calculator',description:'Evaluate basic arithmetic. Expression may contain numbers, parentheses and + - * / % **.',parameters:{type:'object',properties:{expression:{type:'string'}},required:['expression']}},
{name:'current_time',description:'Get current local date and time.',parameters:{type:'object',properties:{}}}
];
function runTool(name,args={}){if(name==='memory_save'){state.memories.unshift({title:String(args.title).slice(0,100),content:String(args.content).slice(0,2000),created:new Date().toISOString()});return 'Saved to encrypted memory.'}if(name==='memory_search'){const q=String(args.query||'').toLowerCase();return state.memories.filter(m=>(m.title+' '+m.content).toLowerCase().includes(q)).slice(0,8)}if(name==='task_add'){state.tasks.push({title:String(args.title).slice(0,160),detail:String(args.detail||'').slice(0,1000),done:false});return 'Task added.'}if(name==='task_complete'){const q=String(args.title||'').toLowerCase(),t=state.tasks.find(x=>x.title.toLowerCase().includes(q));if(!t)return 'No matching task.';t.done=true;return `Completed: ${t.title}`}if(name==='propose_sensitive_action'){pendingApproval={action:String(args.action).slice(0,300),reason:String(args.reason).slice(0,500)};showApproval();return 'Paused for explicit user approval. Nothing executed.'}if(name==='task_list')return state.tasks.filter(t=>args.include_done||!t.done);if(name==='current_time')return new Date().toString();if(name==='calculator'){const x=String(args.expression||'');if(!/^[\d\s()+\-*/%.]+$/.test(x))throw Error('Unsafe expression');return Function(`"use strict";return (${x})`)()}throw Error('Unknown tool')}
function fallback(text){const lower=text.toLowerCase();const actions=[];let reply='I am in offline fallback mode. Connect a Token Harbor key in Settings for open-ended planning.';if(/remember|save (this|that|note)/i.test(text)){const content=text.replace(/^(please\s+)?(remember|save (this|that|note))[:\s-]*/i,'');actions.push({name:'memory_save',arguments:{title:'Conversation note',content}});reply='Saved that to encrypted memory.'}else if(/add (a )?task|todo/i.test(text)){const title=text.replace(/^.*?(task|todo)[:\s-]*/i,'');actions.push({name:'task_add',arguments:{title:title||text}});reply='Added it to your task list.'}else if(/what.*remember|search memory/i.test(lower)){const q=text.replace(/^.*?(remember|memory)\s*/i,'');const found=runTool('memory_search',{query:q});reply=found.length?found.map(x=>`${x.title}: ${x.content}`).join('\n'):'I did not find a matching memory.';return {reply,actions:[]}}return {reply,actions}}
async function modelCall(messages,tools=true){const body={model:$('#model').value||'deepseek-v4.1-flash:free',messages,temperature:.2};if(tools)body.tools=toolDefs.map(f=>({type:'function',function:f}));const endpoint=provider==='openrouter'?'https://openrouter.ai/api/v1/chat/completions':'https://tokenharbor.ai/v1/chat/completions';const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${apiKey}`},body:JSON.stringify(body)});if(!r.ok)throw Error(`Model request failed (${r.status})`);const data=await r.json();return data.choices?.[0]?.message||{} }
async function agentRun(text){const history=state.messages.slice(-12).map(m=>({role:m.role,content:m.content}));const memoryContext=state.memories.slice(0,12).map(m=>`- ${m.title}: ${m.content}`).join('\n')||'(none)';const taskContext=state.tasks.filter(t=>!t.done).slice(0,12).map(t=>`- ${t.title}`).join('\n')||'(none)';const system=`You are Relay, a warm but clipped local-first personal agent. Use stored memory naturally when relevant and mention the useful connection, never the storage mechanism. Proactively suggest one concrete next step when open goals make it timely, without nagging. Use tools when useful. For any external message, public share, destructive operation, purchase, credential use, or privacy-sensitive action, you MUST call propose_sensitive_action and pause for explicit approval; never imply it happened. Never claim web research: network research is unavailable in this client. Keep the final response direct.\nKnown context:\n${memoryContext}\nOpen follow-through:\n${taskContext}`;
if(!apiKey){const out=fallback(text);for(const a of out.actions){trace(`Running ${a.name}…`);runTool(a.name,a.arguments)}await persist();return out.reply}
trace('Planning with model…');const first=await modelCall([{role:'system',content:system},...history],true);const calls=first.tool_calls||[];if(!calls.length)return first.content||'No response returned.';const transcript=[{role:'system',content:system},...history,first];for(const call of calls.slice(0,6)){let args={};try{args=JSON.parse(call.function.arguments||'{}')}catch{}trace(`Running ${call.function.name}…`);let result;try{result=runTool(call.function.name,args)}catch(e){result={error:e.message}}transcript.push({role:'tool',tool_call_id:call.id,content:JSON.stringify(result)})}await persist();trace('Writing response…');const final=await modelCall(transcript,false);return final.content||`Completed ${calls.length} action${calls.length===1?'':'s'}.`}
async function send(text){if(busy)return;busy=true;state.messages.push({role:'user',content:text});renderMessages();await persist();$('#send').disabled=true;try{const reply=await agentRun(text);state.messages.push({role:'assistant',content:reply});await persist();render()}catch(e){state.messages.push({role:'assistant',content:`I could not complete that: ${e.message}`});await persist();render()}finally{busy=false;trace('');$('#send').disabled=false}}
$('#unlock').onclick=unlock;$('#passphrase').onkeydown=e=>{if(e.key==='Enter')unlock()};$('#lockNow').onclick=lock;
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.panel).classList.add('active')});
$('#composer').onsubmit=e=>{e.preventDefault();const v=$('#input').value.trim();if(v){$('#input').value='';send(v)}};$('#input').oninput=e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,120)+'px'};
$$('.prompts button').forEach(b=>b.onclick=()=>send(b.textContent));$('#newChat').onclick=async()=>{state.messages=[];await persist();$('#messages').innerHTML='<div class="welcome"><div class="orb"><span></span></div><h1>Fresh thread.</h1><p>Your encrypted memory and tasks are still available to the agent.</p></div>'};
$('#addMemory').onclick=async()=>{const content=prompt('Memory to save');if(content){state.memories.unshift({title:'Manual note',content,created:new Date().toISOString()});await persist();render()}};$('#addTask').onclick=async()=>{const title=prompt('Task');if(title){state.tasks.push({title,detail:'',done:false});await persist();render()}};
document.addEventListener('click',async e=>{const m=e.target.dataset.delM,t=e.target.dataset.delT,tg=e.target.dataset.toggleT;if(m!==undefined)state.memories.splice(+m,1);else if(t!==undefined)state.tasks.splice(+t,1);else if(tg!==undefined)state.tasks[+tg].done=!state.tasks[+tg].done;else return;await persist();render()});
$('#connectKey').onclick=()=>{const v=$('#apiKey').value.trim();if(v.length<12){$('#keyStatus').textContent='That key looks incomplete.';return}apiKey=v;provider=$('#provider').value;$('#apiKey').value='';$('#keyStatus').textContent='Connected for this tab. Not stored.';$('#modelBadge').textContent=`${provider==='openrouter'?'OpenRouter':'Token Harbor'} · connected`;loadModels()};$('#forgetKey').onclick=()=>{apiKey='';$('#apiKey').value='';$('#keyStatus').textContent='Key forgotten.';$('#modelBadge').textContent='Fallback brain'};
$('#exportData').onclick=async()=>{const pack=await encryptData(state,key,unb64(JSON.parse(localStorage.getItem(META_KEY)).salt));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(pack,null,2)],{type:'application/json'}));a.download=`relay-encrypted-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=async e=>{const f=e.target.files[0];if(!f||f.size>2e6)return alert('Choose an encrypted Relay export under 2 MB.');try{const pack=JSON.parse(await f.text());if(pack.format!=='relay-encrypted-v1')throw Error();const imported=await decryptData(pack,key);if(!Array.isArray(imported.memories)||!Array.isArray(imported.tasks))throw Error();state=imported;await persist();render();alert('Encrypted workspace imported.')}catch{alert('Import failed. This file may use a different passphrase or be invalid.')}e.target.value=''};
$('#allowApproval').onclick=async()=>{if(!pendingApproval)return;state.messages.push({role:'assistant',content:`Approved: ${pendingApproval.action}. This local build records approval but has no external executor, so nothing was sent or changed outside Relay.`});pendingApproval=null;$('#approval').classList.add('hidden');await persist();render()};$('#denyApproval').onclick=()=>{pendingApproval=null;$('#approval').classList.add('hidden')};
$('#changePass').onclick=()=>alert('Export this workspace, lock it, clear site data, then import after creating the new encrypted workspace.');
const fallbackModels={tokenharbor:[['deepseek-v4.1-flash:free','DeepSeek V4.1 Flash'],['muse-spark','Muse Spark'],['kimi','Kimi'],['glm','GLM'],['gemini','Gemini']],openrouter:[['deepseek/deepseek-chat-v3.1:free','DeepSeek Chat V3.1'],['openai/gpt-oss-20b:free','GPT OSS 20B']]};
function paintModels(items){const free=items.filter(x=>x[0].endsWith(':free')),paid=items.filter(x=>!x[0].endsWith(':free'));$('#model').innerHTML=`<optgroup label="FREE">${free.map(x=>`<option value="${esc(x[0])}">${esc(x[1])} · FREE</option>`).join('')}</optgroup><optgroup label="PAID">${paid.map(x=>`<option value="${esc(x[0])}">${esc(x[1])}</option>`).join('')}</optgroup>`}
async function loadModels(){provider=$('#provider').value;paintModels(fallbackModels[provider]);const url=provider==='openrouter'?'https://openrouter.ai/api/v1/models':'https://tokenharbor.ai/v1/models';try{const headers=apiKey?{'Authorization':`Bearer ${apiKey}`}:{},r=await fetch(url,{headers});if(!r.ok)throw Error();const data=await r.json(),rows=(data.data||data.models||[]).map(m=>[m.id,m.name||m.id]).filter(x=>x[0]);if(rows.length)paintModels(rows.sort((a,b)=>(b[0].endsWith(':free')-a[0].endsWith(':free'))||a[1].localeCompare(b[1])))}catch{$('#keyStatus').textContent='Using the built-in catalog until the live catalog is available.'}}
$('#provider').onchange=()=>{apiKey='';$('#apiKey').value='';$('#modelBadge').textContent='Fallback brain';loadModels()};
window.addEventListener('beforeunload',()=>{apiKey='';key=null});
